# Generated by Django 4.0.2 on 2022-11-19 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('exam', '0002_theoryquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=10, null=True)),
                ('percentage', models.CharField(max_length=10, null=True)),
                ('time_taken', models.CharField(max_length=10, null=True)),
                ('difficulty', models.CharField(max_length=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date taken')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.teacher')),
            ],
        ),
    ]
