# Generated by Django 4.0.2 on 2022-11-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_creator_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='participated',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
