# Generated by Django 4.0.2 on 2022-11-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_participated_exam_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='duration',
        ),
    ]
