# Generated by Django 4.0.2 on 2022-11-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_exampassed_student_examtaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
